" phwater's vimrc - <midsummereddy@gmail.com>
" Fork me on github : https://github.com/phwater/vimrc

"> Tips :
">   1. Use 'gf' to open vim quickly.
">        ~/.vim/vimrcs/basic.vim      <= basic settings
">        ~/.vim/vimrcs/plugin.vim     <= plugin config
">   2. Use ':tab help xxx' to get the help pages.
">   3. Use ':h index' to see default key-mappings.

"-------------------------------------------------------------------------------
" Most important setting!
"-------------------------------------------------------------------------------
"> Get out of VI's compatible mode..
if (0 != &compatible)
    set nocompatible
endif

"> Use bash
set shell=/bin/bash

"> Set mapleader
let mapleader=","

"> Source util.vim
source ~/.vim/vimrcs/utils.vim

"-------------------------------------------------------------------------------
" Quickly edit vimrc
"-------------------------------------------------------------------------------
"> fast edit vimrc
if _phwater_getSystemType() == 'linux'
    "Fast editing of .vimrc
    nnoremap <silent> <Leader>ee :call _phwater_switchToBuf("~/.vimrc")<CR>
    nnoremap <silent> <Leader>eb :call _phwater_switchToBuf("~/.vim/vimrcs/basic.vim")<CR>
    nnoremap <silent> <Leader>ep :call _phwater_switchToBuf("~/.vim/vimrcs/plugin.vim")<CR>
    "Fast reloading of the .vimrc
    nnoremap <silent> <Leader>ss :source ~/.vimrc<CR><Bar>:AirlineRefresh<CR>
endif

"-------------------------------------------------------------------------------
" Terminal settings
"-------------------------------------------------------------------------------
set t_Co=256
"set t_ti= t_te=

"> see http://superuser.com/questions/553601/vim-has-unexpected-key-presses-on
"          -startup-what-could-be-causing-this
set t_RV=
set ttymouse=xterm2

"-------------------------------------------------------------------------------
" Source main configurations
"-------------------------------------------------------------------------------
if _phwater_getSystemType() == 'windows'
    source $VIMRUNTIME/mswin.vim
    behave mswin
endif

source ~/.vim/vimrcs/basic.vim
source ~/.vim/vimrcs/plugin.vim
